### ISSUE TITLE
Add a middle name

### ISSUE THREAD

**Issue by gdequillacq** [maximeLeurent/ContactGontran#5]
J'aimerais ajouter 
self.addWidget( "MiddleName", firstFieldsLayout) 
un peu partout, mais j'ai peur de bousiller ton travail.

Avantage de Git me diras-tu... ca n'arrivera pas, hein?
Allez, j'essaie

**Comment by gdequillacq** [comment]
Have not this area in contact.py in the table definition:

def __str__(self):
        output = ""
        if self.firstName is None and self.lastName is None :
            return ""
        elif self.firstName is None:
            return self.lastName
        elif self.lastName is None:
            return self.firstName
        else:
            return self.firstName +" " + self.lastName

**Comment by gdequillacq** [comment]
OK, j'ai sauvegarde dans Atom et essaye de lancer. Et bien sur ca bug au lancement:


E&G@NewPC2014 MINGW64 ~/OneDrive/NavesinkContactList/ContactGontran (dev)
$ python MainWindow.py
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\relationships.py", line 2082, in _determine_joins
    consider_as_foreign_keys=consider_as_foreign_keys
  File "<string>", line 2, in join_condition
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\sql\selectable.py", line 979, in _join_condition
    (a.description, b.description, hint))
sqlalchemy.exc.NoForeignKeysError: Can't find any foreign key relationships between 'Company' and 'contact'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MainWindow.py", line 111, in <module>
    mainWin = MainWindow()
  File "MainWindow.py", line 44, in __init__
    self.dbProcessor = DbProcessor(self)
  File "C:\Users\E&G\OneDrive\NavesinkContactList\ContactGontran\BDD\DbProcessor.py", line 8, in __init__
    self.engine, self.session, self.SessionClass= createBDD()
  File "C:\Users\E&G\OneDrive\NavesinkContactList\ContactGontran\BDD\bdd.py", line 125, in createBDD
    if beta and len(session.query(Contact).all()) == 0:
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\session.py", line 1399, in query
    return self._query_cls(entities, self, **kwargs)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\query.py", line 140, in __init__
    self._set_entities(entities)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\query.py", line 151, in _set_entities
    self._set_entity_selectables(self._entities)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\query.py", line 181, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\query.py", line 3619, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py", line 767, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\mapper.py", line 1994, in _with_polymorphic_mappers
    configure_mappers()
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\mapper.py", line 3013, in configure_mappers
    mapper._post_configure_properties()
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\mapper.py", line 1811, in _post_configure_properties
    prop.init()
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\interfaces.py", line 184, in init
    self.do_init()
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\relationships.py", line 1656, in do_init
    self._setup_join_conditions()
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\relationships.py", line 1731, in _setup_join_conditions
    can_be_synced_fn=self._columns_are_mapped
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\relationships.py", line 1998, in __init__
    self._determine_joins()
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\orm\relationships.py", line 2103, in _determine_joins
    "specify a 'primaryjoin' expression." % self.prop)
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship Compagny.contactsWorking - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.

**Comment by maximeLeurent** [comment]
close, commit : 879166c4d837031bc3a2de1bc18e9c3e87049799
