### ISSUE TITLE
"Compagny" -> "Company"

### ISSUE THREAD

**Issue by gdequillacq** [maximeLeurent/ContactGontran#6]
Je vais essayer aussi: 
"Compagny" -> "Company" 
etc.

**Comment by gdequillacq** [comment]
J'ai fait un Find & Replace pour Compagny, mais n'ai pas change le nom du fichier Compagny.py

**Comment by gdequillacq** [comment]
Ca bug encore un peu. LA, j'ai un peu plus de mal:


$ python MainWindow.py
Traceback (most recent call last):
  File "MainWindow.py", line 111, in <module>
    mainWin = MainWindow()
  File "MainWindow.py", line 44, in __init__
    self.dbProcessor = DbProcessor(self)
  File "C:\Users\E&G\OneDrive\NavesinkContactList\ContactGontran\BDD\DbProcessor.py", line 8, in __init__
    self.engine, self.session, self.SessionClass= createBDD()
  File "C:\Users\E&G\OneDrive\NavesinkContactList\ContactGontran\BDD\bdd.py", line 120, in createBDD
    Base.metadata.create_all(engine)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 4004, in create_all
    tables=tables)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\sql\visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\sql\ddl.py", line 736, in visit_metadata
    [t for t in tables if self._can_create_table(t)])
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\sql\ddl.py", line 1095, in sort_tables_and_constraints
    dependent_on = fkc.referred_table
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 3002, in referred_table
    return self.elements[0].column.table
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py", line 767, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 1891, in column
    tablekey)
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'contactPresCompany.company_id' could not find table 'company' with which to generate a foreign key to target column 'id_'

**Comment by maximeLeurent** [comment]
Toutes les traceback mentionnant "sqlalchemy" sont liées à la base de données. Malheureusement les tracebacks de cette librairy sont assez illisibles.
Il faut comprendre ici que le base de donnée ne peut se créer car il y a des incohérences entre les tables et les déclaration.

l'erreur doit etre liée à aux lignes :
dans class Contact :
  compagniesPresented = relationship("Compagny", secondary="contactPresCompagny")

et la table de lien contactPresCompagny:
contactPresCompagny = Table('contactPresCompagny', Base.metadata,
    Column('contact_id', Integer, ForeignKey('contact.id_')),
    Column('compagny_id', Integer, ForeignKey('compagny.id_'))
)

**Comment by maximeLeurent** [comment]
Une autre solution aurait pu etre de ne modifier que le nom présenté dans l'ihm et garder la faute d'orthographe dans les lignes de codes. C'est généralement à voir en fonction de la tache liée à son changement et le degrée de "sale" que cela ajoute.

dictDisplayName = {
"company" : "Company",
}

**Comment by maximeLeurent** [comment]
Correction complete, procedure:
1) replace All "Compagny" with case and whole word
2) replace All "compagny" with case and whole word
1) replace All "Compagny" with case
2) replace All "compagny" with case

commit 9c8acd5d6025db899f98b5ef21e2e47520f6b541
